name: Build sillyGirl

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - uses: actions/setup-go@v2
      with:
         go-version: '^1.16.7' # The Go version to download (if necessary) and use.
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install bison ed gawk gcc libc6-dev make       
    - name: Clone source code
      run: |
        git clone --depth=1 https://github.com/qtest3/young1_go_silly.git /home/runner/go/src/github.com/qtest3/young1_go_silly
    - name: Build Firmware
      run: |
        mkdir -p /home/runner/go/src/github.com/qtest3/young1_go_silly/develop
        cp $GITHUB_WORKSPACE/dev.go /home/runner/go/src/github.com/qtest3/young1_go_silly/
        cd /home/runner/go/src/github.com/qtest3/young1_go_silly/develop
        git clone https://github.com/qtest3/young1_go_jd
        cd /home/runner/go/src/github.com/qtest3/young1_go_silly
        go build
        mkdir -p /opt/images
        sudo mv -f /home/runner/go/src/github.com/qtest3/young1_go_silly/sillyGirl /opt/images/
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: sillyGirl-packages
        path: /opt/images/
